dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install pip -U
  - pip install -r requirements-dev.txt
script:
  - flake8 --ignore=E501 --statistics jsonextra/
  - pytest --cov=jsonextra tests/
after_success:
  - coveralls
  - codecov
