dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install pip -U
  - pip install pytest
  - pip install coverage
  - pip install pytest-cov
  - pip install coveralls
  - pip install -r requirements.txt
script:
  - pytest --cov=jsonextra tests/
after_sucess:
  coveralls
